builtin.module attributes {ac.contract_epoch = "0.3"} {
  ac.type_scope @types {
    ac.struct @MicroOp fields [{name = "cluster", type = i2}, {name = "rob_tag", type = i16}, {name = "operands_ready", type = i1}, {name = "exec_latency", type = i8}, {name = "value", type = i32}]
  } {dlti.dl_spec = #dlti.dl_spec<
    !ac.struct<@types::@MicroOp> = {abi_alignment = 4 : i64, endianness = "little", preferred_alignment = 4 : i64, size = 12 : i64}
  >}
  ac.system @davincioo_dual_cluster_system root @davincioo_dual_cluster as "davincioo_dual_cluster" tick 0 "cycle" seed {kind = "fixed", value = 0 : i64} instrumentation [] results {id = "default", format = "json"} selected true
  ac.module @davincioo_dual_cluster() parameters {} graph {
    %q0 = ac.v03.source "b0" : !ac.queue_v03<!ac.struct<@types::@MicroOp>, #ac.queue_contract<depth = 1, latency = 1, rate = 1, domain = @core, ordering = fifo>>
    %q1 = ac.compute %q0 {
    ^bb0(%v0: !ac.var<!ac.struct<@types::@MicroOp>>):
      %v1 = ac.var.get %v0 field "cluster" : !ac.var<!ac.struct<@types::@MicroOp>> -> !ac.var<i2>
      %v2 = ac.var.get %v0 field "rob_tag" : !ac.var<!ac.struct<@types::@MicroOp>> -> !ac.var<i16>
      %v3 = ac.var.get %v0 field "operands_ready" : !ac.var<!ac.struct<@types::@MicroOp>> -> !ac.var<i1>
      %v4 = ac.var.get %v0 field "exec_latency" : !ac.var<!ac.struct<@types::@MicroOp>> -> !ac.var<i8>
      %v5 = ac.var.get %v0 field "value" : !ac.var<!ac.struct<@types::@MicroOp>> -> !ac.var<i32>
      %v6 = ac.var.constant 1 : i32 as !ac.var<i32>
      %v7 = ac.var.binary "add" %v5, %v6 : (!ac.var<i32>) -> !ac.var<i32> rhs !ac.var<i32>
      %v8 = ac.var.struct ["cluster", "rob_tag", "operands_ready", "exec_latency", "value"](%v1, %v2, %v3, %v4, %v7) : (!ac.var<i2>, !ac.var<i16>, !ac.var<i1>, !ac.var<i8>, !ac.var<i32>) -> !ac.var<!ac.struct<@types::@MicroOp>>
      ac.var.yield %v8 : !ac.var<!ac.struct<@types::@MicroOp>>
    } : (!ac.queue_v03<!ac.struct<@types::@MicroOp>, #ac.queue_contract<depth = 1, latency = 1, rate = 1, domain = @core, ordering = fifo>>) -> !ac.queue_v03<!ac.struct<@types::@MicroOp>, #ac.queue_contract<depth = 1, latency = 1, rate = 1, domain = @core, ordering = fifo>>
    %q2, %q3, %q4, %q5 = ac.v03.route %q1 by (#ac.field<root = !ac.struct<@types::@MicroOp>, path = ["cluster"], leaf = i2>) : (!ac.queue_v03<!ac.struct<@types::@MicroOp>, #ac.queue_contract<depth = 1, latency = 1, rate = 1, domain = @core, ordering = fifo>>) -> (!ac.queue_v03<!ac.struct<@types::@MicroOp>, #ac.queue_contract<depth = 1, latency = 1, rate = 1, domain = @core, ordering = fifo>>, !ac.queue_v03<!ac.struct<@types::@MicroOp>, #ac.queue_contract<depth = 1, latency = 1, rate = 1, domain = @core, ordering = fifo>>, !ac.queue_v03<!ac.struct<@types::@MicroOp>, #ac.queue_contract<depth = 1, latency = 1, rate = 1, domain = @core, ordering = fifo>>, !ac.queue_v03<!ac.struct<@types::@MicroOp>, #ac.queue_contract<depth = 1, latency = 1, rate = 1, domain = @core, ordering = fifo>>)
    %q7, %q8, %q9, %q10 = ac.v03.issue enqueue (%q2, %q3, %q4, %q5 : !ac.queue_v03<!ac.struct<@types::@MicroOp>, #ac.queue_contract<depth = 1, latency = 1, rate = 1, domain = @core, ordering = fifo>>, !ac.queue_v03<!ac.struct<@types::@MicroOp>, #ac.queue_contract<depth = 1, latency = 1, rate = 1, domain = @core, ordering = fifo>>, !ac.queue_v03<!ac.struct<@types::@MicroOp>, #ac.queue_contract<depth = 1, latency = 1, rate = 1, domain = @core, ordering = fifo>>, !ac.queue_v03<!ac.struct<@types::@MicroOp>, #ac.queue_contract<depth = 1, latency = 1, rate = 1, domain = @core, ordering = fifo>>) wakeup (%q6 : !ac.queue_v03<!ac.struct<@types::@MicroOp>, #ac.queue_contract<depth = 1, latency = 1, rate = 1, domain = @core, ordering = fifo>>) entries 24 width 3 policy "oldest_ready" -> issued (!ac.queue_v03<!ac.struct<@types::@MicroOp>, #ac.queue_contract<depth = 1, latency = 1, rate = 1, domain = @core, ordering = fifo>>, !ac.queue_v03<!ac.struct<@types::@MicroOp>, #ac.queue_contract<depth = 1, latency = 1, rate = 1, domain = @core, ordering = fifo>>, !ac.queue_v03<!ac.struct<@types::@MicroOp>, #ac.queue_contract<depth = 1, latency = 1, rate = 1, domain = @core, ordering = fifo>>, !ac.queue_v03<!ac.struct<@types::@MicroOp>, #ac.queue_contract<depth = 1, latency = 1, rate = 1, domain = @core, ordering = fifo>>) {dependency_key = #ac.field<root = !ac.struct<@types::@MicroOp>, path = ["rob_tag"], leaf = i16>, dependency_ready = #ac.field<root = !ac.struct<@types::@MicroOp>, path = ["operands_ready"], leaf = i1>, wakeup_key = #ac.field<root = !ac.struct<@types::@MicroOp>, path = ["rob_tag"], leaf = i16>}
    %q11, %q12 = ac.v03.engine (%q7, %q8) latency_by (#ac.field<root = !ac.struct<@types::@MicroOp>, path = ["exec_latency"], leaf = i8>) inflight 8 initiation_interval 1 kind "integer" : (!ac.queue_v03<!ac.struct<@types::@MicroOp>, #ac.queue_contract<depth = 1, latency = 1, rate = 1, domain = @core, ordering = fifo>>, !ac.queue_v03<!ac.struct<@types::@MicroOp>, #ac.queue_contract<depth = 1, latency = 1, rate = 1, domain = @core, ordering = fifo>>) -> (!ac.queue_v03<!ac.struct<@types::@MicroOp>, #ac.queue_contract<depth = 1, latency = 1, rate = 1, domain = @core, ordering = fifo>>, !ac.queue_v03<!ac.struct<@types::@MicroOp>, #ac.queue_contract<depth = 1, latency = 1, rate = 1, domain = @core, ordering = fifo>>)
    %q16, %q17 = ac.v03.fork %q11 : (!ac.queue_v03<!ac.struct<@types::@MicroOp>, #ac.queue_contract<depth = 1, latency = 1, rate = 1, domain = @core, ordering = fifo>>) -> (!ac.queue_v03<!ac.struct<@types::@MicroOp>, #ac.queue_contract<depth = 1, latency = 1, rate = 1, domain = @core, ordering = fifo>>, !ac.queue_v03<!ac.struct<@types::@MicroOp>, #ac.queue_contract<depth = 1, latency = 1, rate = 1, domain = @core, ordering = fifo>>)
    %q18, %q19 = ac.v03.fork %q12 : (!ac.queue_v03<!ac.struct<@types::@MicroOp>, #ac.queue_contract<depth = 1, latency = 1, rate = 1, domain = @core, ordering = fifo>>) -> (!ac.queue_v03<!ac.struct<@types::@MicroOp>, #ac.queue_contract<depth = 1, latency = 1, rate = 1, domain = @core, ordering = fifo>>, !ac.queue_v03<!ac.struct<@types::@MicroOp>, #ac.queue_contract<depth = 1, latency = 1, rate = 1, domain = @core, ordering = fifo>>)
    %q13, %q14 = ac.v03.engine (%q9, %q10) latency_by (#ac.field<root = !ac.struct<@types::@MicroOp>, path = ["exec_latency"], leaf = i8>) inflight 12 initiation_interval 2 kind "vector" : (!ac.queue_v03<!ac.struct<@types::@MicroOp>, #ac.queue_contract<depth = 1, latency = 1, rate = 1, domain = @core, ordering = fifo>>, !ac.queue_v03<!ac.struct<@types::@MicroOp>, #ac.queue_contract<depth = 1, latency = 1, rate = 1, domain = @core, ordering = fifo>>) -> (!ac.queue_v03<!ac.struct<@types::@MicroOp>, #ac.queue_contract<depth = 1, latency = 1, rate = 1, domain = @core, ordering = fifo>>, !ac.queue_v03<!ac.struct<@types::@MicroOp>, #ac.queue_contract<depth = 1, latency = 1, rate = 1, domain = @core, ordering = fifo>>)
    %q20, %q21 = ac.v03.fork %q13 : (!ac.queue_v03<!ac.struct<@types::@MicroOp>, #ac.queue_contract<depth = 1, latency = 1, rate = 1, domain = @core, ordering = fifo>>) -> (!ac.queue_v03<!ac.struct<@types::@MicroOp>, #ac.queue_contract<depth = 1, latency = 1, rate = 1, domain = @core, ordering = fifo>>, !ac.queue_v03<!ac.struct<@types::@MicroOp>, #ac.queue_contract<depth = 1, latency = 1, rate = 1, domain = @core, ordering = fifo>>)
    %q22, %q23 = ac.v03.fork %q14 : (!ac.queue_v03<!ac.struct<@types::@MicroOp>, #ac.queue_contract<depth = 1, latency = 1, rate = 1, domain = @core, ordering = fifo>>) -> (!ac.queue_v03<!ac.struct<@types::@MicroOp>, #ac.queue_contract<depth = 1, latency = 1, rate = 1, domain = @core, ordering = fifo>>, !ac.queue_v03<!ac.struct<@types::@MicroOp>, #ac.queue_contract<depth = 1, latency = 1, rate = 1, domain = @core, ordering = fifo>>)
    %q6 = ac.v03.merge (%q16, %q18, %q20, %q22) policy (#ac.policy<kind = round_robin>) : (!ac.queue_v03<!ac.struct<@types::@MicroOp>, #ac.queue_contract<depth = 1, latency = 1, rate = 1, domain = @core, ordering = fifo>>, !ac.queue_v03<!ac.struct<@types::@MicroOp>, #ac.queue_contract<depth = 1, latency = 1, rate = 1, domain = @core, ordering = fifo>>, !ac.queue_v03<!ac.struct<@types::@MicroOp>, #ac.queue_contract<depth = 1, latency = 1, rate = 1, domain = @core, ordering = fifo>>, !ac.queue_v03<!ac.struct<@types::@MicroOp>, #ac.queue_contract<depth = 1, latency = 1, rate = 1, domain = @core, ordering = fifo>>) -> !ac.queue_v03<!ac.struct<@types::@MicroOp>, #ac.queue_contract<depth = 1, latency = 1, rate = 1, domain = @core, ordering = fifo>>
    %q15 = ac.v03.reorder completed (%q17, %q19, %q21, %q23) by (#ac.field<root = !ac.struct<@types::@MicroOp>, path = ["rob_tag"], leaf = i16>) entries 48 width 2 policy "in_order" : (!ac.queue_v03<!ac.struct<@types::@MicroOp>, #ac.queue_contract<depth = 1, latency = 1, rate = 1, domain = @core, ordering = fifo>>, !ac.queue_v03<!ac.struct<@types::@MicroOp>, #ac.queue_contract<depth = 1, latency = 1, rate = 1, domain = @core, ordering = fifo>>, !ac.queue_v03<!ac.struct<@types::@MicroOp>, #ac.queue_contract<depth = 1, latency = 1, rate = 1, domain = @core, ordering = fifo>>, !ac.queue_v03<!ac.struct<@types::@MicroOp>, #ac.queue_contract<depth = 1, latency = 1, rate = 1, domain = @core, ordering = fifo>>) -> !ac.queue_v03<!ac.struct<@types::@MicroOp>, #ac.queue_contract<depth = 1, latency = 1, rate = 2, domain = @core, ordering = fifo>>
    ac.v03.sink %q15 : !ac.queue_v03<!ac.struct<@types::@MicroOp>, #ac.queue_contract<depth = 1, latency = 1, rate = 2, domain = @core, ordering = fifo>>
    ac.return
  }
}
